name: wf
on: 
  workflow_call:
    secrets:
      ABC:
        description: something
jobs:
  job0:
    environment: ${{ inputs.environment }}
    runs-on: self-hosted
    steps:
      - name: step0
        run: |
           echo "Hello World!"
           echo "${{ vars.ABC }}"
           echo "${{ inputs.environment }}"
           
