name: wf
on: 
  workflow_call:
    secrets:
      ABC:
        description: something
jobs:
  job0:
    runs-on: self-hosted
    steps:
      - name: step0
        run: |
           echo "Hello World!"
           echo "${{ secrets.ABC }}" | rev
           echo "${{ vars.ABC }}" | rev
           
