name: wf
on: 
  workflow_call:
    inputs:
      host:
        description: registry_host
        required: true
        type: string
jobs:
  job0:
    environment: ${{ inputs.environment }}
    runs-on: self-hosted
    steps:
      - name: step0
        run: |
           echo "${{ inputs.ABC }}"
  job1:
    runs-on: self-hosted
    steps:
      - name: step0
        run: |
           echo "${{ inputs.ABC }}"           
