name: wf
on: 
  workflow_call:
    inputs:
      environment:
        type: string
    secrets:
      ABC:
        description: something
jobs:
  job0:
    environment: ${{ inputs.environment }}
    runs-on: self-hosted
    steps:
      - name: step0
        run: |
           echo "Hello World!"
           echo "${{ secrets.ABC }}" | rev
           echo "${{ vars.ABC }}" | rev
           
