name: wf_0
on: workflow_dispatch
jobs:
  job0:
    environment: abc
    runs-on: self-hosted
    steps:
      - name: step0
        run: |
           echo "Hello World!"
           echo "${{ vars.REPO_VAR }}" | rev
